### ISSUE TITLE
Not Seeing Authentication

### ISSUE THREAD

**Issue by nicolaijohnson** [jhegele/tab-einstein-scenarios#31]
I've downloaded the extension and put it into my Tableau 2020.2 Desktop dashboard, but it's not taking me to the authentication step. Instead, I see a screen that says "Please Complete the Setup Process in order to start generating predictions from Einstein - Open Setup" (first screenshot). If I press on Open Setup, I get an error message (second screenshot).

I found the FAQ on your site with the link to the authentication URL. I was able to see the "Authentication Complete" message here. 

I would like some help so I can use your extension for a prediction model I built in Einstein Discovery. 

<img width="582" alt="Open Setup" src="https://user-images.githubusercontent.com/22534871/85343279-105e1100-b4b2-11ea-9679-15c1bc3392b3.png">

<img width="520" alt="Error Message" src="https://user-images.githubusercontent.com/22534871/85343298-194ee280-b4b2-11ea-9197-2aa6d0c57828.png">

**Comment by jhegele** [comment]
That error message indicates that you have no Tableau Parameters on the dashboard. The extension maps Tableau Parameters to Einstein Model Parameters so you need to have at least one parameter, in Tableau, that corresponds to at least one field in your Einstein Model. Tableau's knowledge base contains [details on how to create and use parameters](https://help.tableau.com/current/pro/desktop/en-us/changing-views-using-parameters.htm).

Once you have a parameter added, try again and you should be allowed to go through the authentication flow.

**Comment by jhegele** [comment]
Closing this issue. If the above recommendation does not work, please feel free to reopen.

**Comment by nicolaijohnson** [comment]
@jhegele, this fixed the issue. I'm able to use the extension. I love it, it's very powerful!

**Comment by jhegele** [comment]
@nicolaijohnson, that's great to hear! 👏  Glad that it's working well for you now.
